var x = document.getElementById("main-header").parentElement.nodeName;
// console.log(x);
// const element = document.getElementById("main-header")
// let html = element.lastElementChild.innerHTML;
// let html1 = element.lastChild.innerHTML;
// console.log(html);
// const node = document.createElement("li");
// const textnode = document.createTextNode("Water");
// node.appendChild(textnode);
// document.getElementById("items").appendChild(node);
// let text = document.getElementById("items").firstElementChild;
// console.log(text);
// let next = document.getElementById("items").nextSibling;
// console.log(next);
// let text1 = text.nextElementSibling;
// console.log(text1);
// var text3 = document.getElementById("items").previousSibling;
// console.log(text3);
// let text = document.getElementById("items").previousElementSibling;
// console.log(text);
// const para = document.createElement("p");
// para.textContent = "This is a paragraph." ; 
// document.getElementById("myDIV").appendChild(para);
// x.setAttribute("class", "democlass");
// const h1 = document.createElement("h1");
// const textNode = document.createTextNode("Hello World");
// h1.appendChild(textNode);
// const para = document.createElement("p");
// const textNode1 = document.createTextNode("Hello World");
// para.appendChild(textNode);
// const node = document.createElement("li1");
// const textnode = document.createTextNode("Water");
// node.appendChild(textnode);
// document.getElementById("myList").appendChild(node);